from Bio.Seq import Seq

String1 = "TATAGCACGCGACCGGTACCCAGTCAATCGTTGCCCTTGACCGAGTATTCTCAATGCCCGCCCCCAGCACCGAACGTTCCACAATACACCTAAAGTTGAGAGACACGGTTGCAGCCCTGACTATCTACTGTCAGGGATAAGCTAGTCAGCAACAGACTCCTGCGTACGCTAGCGCATGAATCCAAATGGGCTCCAACTATATAGCGTTAAACCTCCGTAGCATGACTGTGGGAATGAAGCTATAGAAGGCTATGCGGCACATCCTGTTATCCGCGCCCAGCAGGCAAAGGAGGCCGGTCCAGCCCACGGACGTTTCCTGATTGCCGTTCTACAGAGTCTTACGTGCGGTAGACTGAGGTAACTCGACACGATGAGAAGTTTGTGTTATGAATGGCATGCTTTAAAGCACACAAGTTGGGCGAGGGTGTCTGACAGGGGTCCGCCAGGCCTCGTTCCAAAATAATGACGGACGAGCTAATAGATACAATACTGCAATCATATCTCTTGTAATACCGTCTAGCATCATATCCACCCAGCCAAGTCCGAGTCTAAGATAACGCTACAAAGGACAGGTACGGGAGCACGACGCTTCCGGAAAGGGCCCAACCTCCCGAGAACAAAGCGACTAAAGCGTTCATCGGCCTATGAAGCTCTTCCGTGTACGAAGAGGCAGTGATTTATATCTCTTAGAATCGCATGCCGCAACGTCGCACCATACGGTCGCAATTCAACCGTGGTCGCCATTTGCGTACCGTTTAGTACTGGTTTGGCTCCCGTCTAAGTGTAATCCCCCCGAAGGGCGCG"

for i in range(len(String1)):
    for length in range(4, 13):  # 4 to 12 inclusive
        if i + length <= len(String1):
            chunk = String1[i:i+length]
            revcomp = str(Seq(chunk).reverse_complement())
            if chunk == revcomp:
                print(f"{i+1} {length}")
