string = "TAGCGACACTTATTAAGCTATGCCCCTTAAATGATCGCTTTTACATATTCCGCGACTGGCTTTCCTAATCGCTTTCATCATTCAGAGAGAGCTAGAAATTTAAAGGGCCTAATATCAGAAGTGTCCTACTATCTCGTCCCTGTTGACTGTTGGGGTGGTCTAACAGCCCTCGGGCTCTAACCGACTTCAAGCTGCTGGCGGTTGCCCACTCTCACCTGGCCCCCGGTCACTCTGTCCGGAACAGGTCTTAGATCGGTTTTCAATTTAGGTACGGCTTTACAGATTTGACGGGATCACCAATCCATGGTAAATAGACATCGCAATCGGTATACAGATTTAAAAGGTGCCGGTATACACACCCGCATACGCGGTCGTGTGTATGTTCAGGCCGTTCAGGTTGGTAAGAAGAGAGTGGGAGCTACGGAAAAACGCTAAGGAACCTCCGGGTCTGGTTTCGGCAACATTACGTACAAATGCTCAAATCTGCTACCATTATGTAGGAGTTATAGTATGACCAAAAAACCGTCTAAACGCTGTATCCTGGCCCCACAGTTACCCGTATCCTTACTTTAGGCGAGGTGACCTTCCAGAGACGACGACGAGAGATAGTACATATACCTTGTATCCCTGGCCACTTCAGTATGCTGCGTTGCAAAATGAGAGCTACAGTGTTGTTACTGCCTCAGCATCTCTATGGAATTATACACGTGCCGTTGAGACAGCCCCTTCTACGCTTGCGGACGGTACGACGTGTATAAATCGTAGGTGGTAAGCGGTTAGCCAGGGGCTCGTTGAGTCGCGGTGCACAGGCGGTACCCATCGTCCCAGGGTGGGTAACTAAATTCGTTTCGGGTCCAACGGGGCAAGCGGTACTCTTCAAAAGTGGGGGACCTTAGCCAAATGCCTTGGGTTGAGAGAGTGAGATAACCGTAGCCGTCCCGGCCA"
string2 = ""




for char in string:
    if char == "A":
        string2 += "T"
    elif char == "T":
         string2 += "A"
    elif char == "C":
         string2 += "G"
    elif char == "G":
         string2 += "C"
reversed_string = string2[::-1]

print(reversed_string)