string = "CTCGCGCCGGTAAGGTCAGCATAACCTCAAAGAGTTAAGGATGGCGTACTAGGACTAGCGTGACGCACCACACTGGGTAAATGTATGCCCCATCTCTATCAAGCTGGTGATGTGAGCAGCGCGCGGTGACTTCCCCCATACTGTCGGATAAACGCGAAGACGCCGGATAATACTTCGGTTGCGACGGCCTGTGTTCATGAGGTGATTCCTCCCAGTGTACCCGGGCCTTGCCCGTTCCCGGCGTGCCTAGCTTATCCTGGCTTTTAACTTGCAGTATGTTAGTGTTATTGACACGAAGATCTGAAAACATCGTTTGTTAGTCACAGACGGTCGGGAGGTGGAGCTCCCATGTAACTTCGGGACTGATTGTTTAGTTGGCTGGCGGATTTATTGCGAGTAAGTGCAAATTGATGTAATTGAATGTCCGAGAACGTAGCGCGACTATGAGACAGTGAGGCCGCGATAATGGAGCGGAGACGCAATCAACTCTACCATAAAGTACTTAGAGTCCAAGCATCGGAGGCGCCCGCTGCAGTCGCCAGTCACGGAACGGCTTTAGCTATAAAGGATAACACCTCAGCCAAGAAATTATCGTCCGACGTTGTAAAAGCGGATGGGAATAATCCGCGTGGAATCTCGTAAGGATAGTGTGTAGCAAACTCTTCCCATGCCGATCAAACGGATCTCTAGAGCACGGTTATACTTGCTGCGCGACCGGGATCTATGAGAGTAGGTTTGTAAGGCGCCTTTAGTCACTGGTCCTGCTGAGTAGATAATTACTTTGGGGTAGATAAGTGAGTCAGGCCACCCTAGCTAGTCCAACCTTCTTTAGCTTTACCCCGGAACAAAGTCCGGCAAATTTGATTGTCTAGTGCAAATAATTAGTGAACTTTATGAACCTTTAGCCTGTTTCATGGACCAATCGAAGATGATTCTGTCTGTAGGTCTGACAGGCGTCTCG"


nucleotide_A = 0
nucleotide_T = 0    
nucleotide_C = 0  
nucleotide_G = 0


for char in string:
    if char == "A":
        nucleotide_A += 1
    elif char == "T":
        nucleotide_T += 1
    elif char == "C":
        nucleotide_C += 1
    elif char == "G":
        nucleotide_G += 1


print(nucleotide_A, nucleotide_C, nucleotide_G, nucleotide_T)
