dna_string = "GACTTGCAGGTTTTTGGACTTGCAACTTGCAACTTGCACACTTGCAGGCCGTTAACTTGCATAGACTTGCAACTTGCATGGGGGCTACTTGCACCCCTAACTTGCAACTTGCAACGGAAATACACTTGCAACTTGCAGGAGACTTGCAACTTGCAAACTTGCATACTTGCACTAGCGTAACTTGCAACTTGCAGTGTACTTGCAAGAGGACTTGCACCACTTGCAAAATCGCTACCAAAGACTTGCACACTTGCACTCACTTGCACAAAACTTGCATGATTAACTTGCACCAGACTTGCAACACTTGCACAGGGTGACTTGCAACTTGCAAACTTGCAAACTTGCATCAGTAGACTTGCAGTTTCGTACTTGCAACTTGCAACTTGCATACTTGCATACTTGCACATATCGTTTGCACTTGCACAACTTGCAGGTACTTGCACCAAATAGAACTTGCAACCATACTTGCAGACACTTGCAACTTGCAACTCTACTTGCAAATCACTTGCAGGACTTGCAACTTGCACACTTGCACAACTTGCATCAAACTTGCAATACGTCCAAACTTGCAACTTGCATTAATACACTTGCACGAACTTGCAGACTTGCAACTTGCACACTTGCACAAACGTCATCTACTTGCAGACACTTGCATAAGACTTGCAACTTGCATACTTGCATACTTGCAACTTGCAACTTGCAACTTGCAACAGACTTGCAACAAGCACTTGCAAAACTTGCAAACTAAAGAACTTGCAGATGGGTGCGACTTGCAACTTGCAACTTGCACAACTTGCACTACTTGCAGCACTTGCAGCACTTGCAACTTGCACCACTTGCA"
motif = "ACTTGCAAC"
def find_motif(dna_string, motif):
    positions = []
    motif_length = len(motif)
    
    for i in range(len(dna_string) - motif_length + 1):
        if dna_string[i:i + motif_length] == motif:
            positions.append(i + 1)  

    return positions
print(find_motif(dna_string, motif))
