string = "GTGCATCGTTATAATCAACTAATAACCTAGGGTCCAGCATGGTCTCGCTATTGTAATCCACTTTGGAGTAGACTCAGCATGTGAACACCGAATAACGAGAGGCAGTGGTCGGATACATCTTCGCTCCTCCATCATCACGTGGTAGGAACCCCACGGAATTTCTCTCATTGAGAGCTGACCTGACTATTTTTAGCATCGGTCTTCACAACATGGTTATACGGAACTGTTGGTCAGCGGCTTGTAAAATCAGAGCCTACTACTGCACCCCCCCGGGATCGGTCGACCTGTACGCGGTCCATTAGCGTCAACCGTCGACATCGAATGCTTTATGACAAGTCTGAGGGTATGCTTCAGAGCCGATACGGAAAGTCTCTGGGCCTTAATGGCAGCGGATACATGCCTATATTAATTCTTGCCGTTCAATTTTTCGGTACACTCAGCTGCTGAGGTTCAACTGGAAAGGACTCTACGGCCAACTTGGTGATGACGTGACCACTAATCATCATTCAACTCTGCACCGGGTACAGTCTACCTGAGGACATCCGTTGACCTTACAAGACTCCAACGACAGGATGGTCGATTTCCACCGTCAAATCAATCTTGTTCACACGCTTCAACCTTAAAGGCAAGCCAGCGCCATGCAGATGTGCGAAGTGGTCCATGGGCTGCTTTCTGACTGAGCGGTGGTTTGCTGAATACGCTCTAAGCATAGAAAACTATGTTACTCAGGGTTGTTGCTAGCCCACATTAGGCGAGTAAATATACATTCGTGTAATAATCCGGATCTTTCCTGTTACAGGCTACCAGATCGAAGACCTGCCCTATTGGACAGATGTTACGAAGCCGAGGCCTATTACATGAATCCTCTGAGAAGTCCAAGTCATGCGGTCTTAGCGTTTCATTCAATAAGTACGCGTGAGTTCGCCAAGCATCGGCTGTTCCATTCATACGGGTGCTCTCTGGCGATTCGTAGTTTTCC"
string2 = ""




for char in string:
    if char == "A":
        string2 += "A"
    elif char == "T":
         string2 += "U"
    elif char == "C":
         string2 += "C"
    elif char == "G":
         string2 += "G"

print(string2)