from Bio.Data import CodonTable
from Bio.Seq import Seq

rna_table = CodonTable.unambiguous_rna_by_id[1]

# 2) build a dict AA ➞ all codons
aa_to_codons = {}

for codon, aa in rna_table.forward_table.items():
    aa_to_codons.setdefault(aa, []).append(codon)

for stop in rna_table.stop_codons:
    aa_to_codons.setdefault('*', []).append(stop)

total_options = 1
protein = Seq("MWDRYNTIIIWQHCEGYVFNIQAGSLRVVDLIVTQQTKECISVVIKRTLTLEPPYYQRQLGLNPAPCRENNYIRKTKRQWVVRVVATYNSEMIPMTFRIQDIQNYFRVYWQWVVYSCWNGTFIWNQEHMYQTSIFRLQADKGGMMAMWDFYATHPMYYPYTFCAYMECTMASYAYSHGKLLMPFALWDSSISKGPSHYLNRFDYGSLMIKMVIDTDHPFESSAYKRRKWWNMCWAECCDEYMPRSAHARWHWDELICWCSYHQFGSDFKKVFRQFDEQNNCGAMVRAMLCGWELAEEVVKNFDSHQQCPWVLVTFMRGATHYYPTWLYKDFFFAEQLLDDKHPLYFASPHWCHCNCINISYNRASFAKIADEVQNAYNCDIIFSFMRLYFGKHTNGHTCITRNWWWMCSEHSPNCKTAHISHGQWCRDPYQCIIKDTIVAVMRNPELTTIEKTAHFHLKFSRWVIGVDMWAYIIVSQDTTSAFCYFLTHNGHYLQDNYQLNEQTMRDRFMPDGWGKWWDNKWHVDAIFMQHVWLPYRTKMCDDSILHNCWGLDFKGNREGAGMVEMNRRIHAVNDPGRIDEILETMCICEGARRIWWANISAWGSYELAVHTMHQCYNANIEGCEMRFVYHTVTGHQWEVFFMHINYDDAKNPYHKFEPTYLFAPRTWHFGKIPLRPKWFISPDIHLPRWAAECDRVFMFCELLWCYLNSRCVPDCDPWPQMTRDSQWCVQADNMWQNGKGTPTRTWVFAFRYDAYWYPMPFWPKMKAYCDRYRMARCIQCTIKNPFAPAYDARAEPADQNNNGGLVFGQRCNSGVFLIGNVQFVQENYTLECLWWMTMGTYYKGCMLHLNFCVNKKMNHIEMAKQPAWTQMNVHCGLGMAWEQSGLINYQYWCCMQCRQNWTDYHRGYTTNMHWLTAGECFRDFALVELLAVCFIVGTTVWECPCTEEEIYHLRWMEFCQLRVMIHYIIYHGSMNQMRNNTYDDPKSIFVTSDPSHF")  # your full protein
for i, aa in enumerate(protein, start=1):
    possible = aa_to_codons.get(aa, [])
    n = len(possible)
    total_options *= n
print({total_options})
